sudo: required
services:
  - docker

env:
    matrix:
      - OS=centos DIST=6 PACK=rpm
      - OS=centos DIST=7 PACK=rpm
      - OS=fedora DIST=22 PACK=rpm
      - OS=fedora DIST=23 PACK=rpm
      - OS=fedora DIST=24 PACK=rpm
      - OS=fedora DIST=rawhide PACK=rpm
      - OS=ubuntu DIST=trusty PACK=deb
      - OS=ubuntu DIST=precise PACK=deb
      - OS=ubuntu DIST=wily PACK=deb
      - OS=ubuntu DIST=xenial PACK=deb
      - OS=debian DIST=jessie PACK=deb
      - OS=debian DIST=wheezy PACK=deb
      - OS=debian DIST=stretch PACK=deb
      - OS=debian DIST=sid PACK=deb

script:
  - git clone https://github.com/tarantool/build.git
  - ./build/pack/travis.sh

notifications:
  email: true
  irc: false
