# minc-toolkit configuration parameters for @MINC_TOOLKIT_VERSION_FULL@

export MINC_TOOLKIT_VERSION="@MINC_TOOLKIT_VERSION_FULL@"
export PATH=@CMAKE_INSTALL_PREFIX@/bin:${PATH}
export PERL5LIB=@CMAKE_INSTALL_PREFIX@/perl:${PERL5LIB}
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:@CMAKE_INSTALL_PREFIX@/lib:@CMAKE_INSTALL_PREFIX@/lib/InsightToolkit
export MNI_DATAPATH=@CMAKE_INSTALL_PREFIX@/share:${MNI_DATAPATH}
export MINC_FORCE_V2=1
export MINC_COMPRESS=4
export VOLUME_CACHE_THRESHOLD=-1
