# minc-toolkit configuration parameters for @MINC_TOOLKIT_VERSION_FULL@
export MINC_TOOLKIT=@CMAKE_INSTALL_PREFIX@
export MINC_TOOLKIT_VERSION="@MINC_TOOLKIT_VERSION_FULL@"
export PATH=${MINC_TOOLKIT}/bin:${MINC_TOOLKIT}/pipeline:${PATH}
export PERL5LIB=${MINC_TOOLKIT}/perl:${MINC_TOOLKIT}/pipeline${PERL5LIB:+:$PERL5LIB}
export DYLD_LIBRARY_PATH=${MINC_TOOLKIT}/lib@LIB_SUFFIX@:${MINC_TOOLKIT}/lib@LIB_SUFFIX@/InsightToolkit${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}
export MNI_DATAPATH=${MINC_TOOLKIT}/../share:${MINC_TOOLKIT}/share
export MINC_FORCE_V2=1
export MINC_COMPRESS=4
export VOLUME_CACHE_THRESHOLD=-1
export MANPATH=${MINC_TOOLKIT}/man${MANPATH:+:$MANPATH}
# integrated ANTs tools
export ANTSPATH=${MINC_TOOLKIT}/bin
