# minc-toolkit configuration parameters for @MINC_TOOLKIT_VERSION_FULL@
export MINC_TOOLKIT=@CMAKE_INSTALL_PREFIX@
export MINC_TOOLKIT_VERSION="@MINC_TOOLKIT_VERSION_FULL@"
export PATH=${MINC_TOOLKIT}/bin:${MINC_TOOLKIT}/pipeline:${PATH}
export PERL5LIB=${MINC_TOOLKIT}/perl:${MINC_TOOLKIT}/pipeline:${PERL5LIB}
export LD_LIBRARY_PATH=${MINC_TOOLKIT}/lib@LIB_SUFFIX@:${MINC_TOOLKIT}/lib@LIB_SUFFIX@/InsightToolkit:${LD_LIBRARY_PATH}
export MNI_DATAPATH=${MINC_TOOLKIT}/share
export MINC_FORCE_V2=1
export MINC_COMPRESS=4
export VOLUME_CACHE_THRESHOLD=-1
export MANPATH=${MINC_TOOLKIT}/man:${MANPATH}
