macro(build_zlib install_prefix staging_prefix)


# make a custom ZLIB configuration file
# Using zlib-ng (https://github.com/zlib-ng/zlib-ng) in ZLIB_COMPAT mode as a
# drop-in replacement for upstream zlib.

SET (ZLIB_VERSION_STRING 2.3.3)
SET (ZLIB_VERSION_MAJOR  2)
SET (ZLIB_VERSION_MINOR  3)

  if(CMAKE_EXTRA_GENERATOR)
    set(CMAKE_GEN "${CMAKE_EXTRA_GENERATOR} - ${CMAKE_GENERATOR}")
  else()
    set(CMAKE_GEN "${CMAKE_GENERATOR}")
  endif()

  set(CMAKE_EXTERNAL_PROJECT_ARGS
        -DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}
        -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
        -DCMAKE_LINKER:FILEPATH=${CMAKE_LINKER}
        "-DCMAKE_C_FLAGS:STRING=-fPIC ${CMAKE_C_FLAGS}"
        -DCMAKE_C_FLAGS_DEBUG:STRING=${CMAKE_C_FLAGS_DEBUG}
        -DCMAKE_C_FLAGS_MINSIZEREL:STRING=${CMAKE_C_FLAGS_MINSIZEREL}
        -DCMAKE_C_FLAGS_RELEASE:STRING=${CMAKE_C_FLAGS_RELEASE}
        "-DCMAKE_C_FLAGS_RELWITHDEBINFO:STRING=${CMAKE_C_FLAGS_RELWITHDEBINFO}"
        -DCMAKE_EXE_LINKER_FLAGS:STRING=${CMAKE_EXE_LINKER_FLAGS}
        -DCMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=${CMAKE_EXE_LINKER_FLAGS_DEBUG}
        -DCMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=${CMAKE_EXE_LINKER_FLAGS_MINSIZEREL}
        -DCMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=${CMAKE_EXE_LINKER_FLAGS_RELEASE}
        "-DCMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=${CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO}"
        -DCMAKE_MODULE_LINKER_FLAGS:STRING=${CMAKE_MODULE_LINKER_FLAGS}
        -DCMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=${CMAKE_MODULE_LINKER_FLAGS_DEBUG}
        -DCMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=${CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL}
        -DCMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=${CMAKE_MODULE_LINKER_FLAGS_RELEASE}
        "-DCMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=${CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO}"
        -DCMAKE_SHARED_LINKER_FLAGS:STRING=${CMAKE_SHARED_LINKER_FLAGS}
        -DCMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=${CMAKE_SHARED_LINKER_FLAGS_DEBUG}
        -DCMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=${CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL}
        -DCMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=${CMAKE_SHARED_LINKER_FLAGS_RELEASE}
        "-DCMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=${CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO}"
        -DCMAKE_STATIC_LINKER_FLAGS:STRING=${CMAKE_STATIC_LINKER_FLAGS}
        -DCMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=${CMAKE_STATIC_LINKER_FLAGS_DEBUG}
        -DCMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=${CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL}
        -DCMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=${CMAKE_STATIC_LINKER_FLAGS_RELEASE}
        "-DCMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=${CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO}"
        -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
  )
  
  if(APPLE)
    list(APPEND CMAKE_EXTERNAL_PROJECT_ARGS
      -DCMAKE_OSX_ARCHITECTURES:STRING=${CMAKE_OSX_ARCHITECTURES_EXTSEP}
      -DCMAKE_OSX_SYSROOT:STRING=${CMAKE_OSX_SYSROOT}
      -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=${CMAKE_OSX_DEPLOYMENT_TARGET}
    )
  endif()

  GET_PACKAGE("https://github.com/zlib-ng/zlib-ng/archive/refs/tags/2.3.3.tar.gz" "72337e6a7d2662af50a4ed0274c61b7e" "zlib-ng-2.3.3.tar.gz" ZLIB_PATH )

ExternalProject_Add(ZLIB
  URL  "${ZLIB_PATH}"
  URL_MD5 "72337e6a7d2662af50a4ed0274c61b7e"
  UPDATE_COMMAND ""
  SOURCE_DIR ZLIB
  BINARY_DIR ZLIB-build
  LIST_SEPARATOR :::
  CMAKE_GENERATOR ${CMAKE_GEN}
  CMAKE_ARGS
      -DBUILD_SHARED_LIBS:BOOL=OFF
      -DZLIB_COMPAT:BOOL=ON
      -DWITH_GZFILEOP:BOOL=ON
      -DBUILD_TESTING:BOOL=OFF
      -DZLIB_ENABLE_TESTS:BOOL=OFF
      -DWITH_GTEST:BOOL=OFF
      -DWITH_BENCHMARKS:BOOL=OFF
      -DWITH_FUZZERS:BOOL=OFF
      -DCMAKE_INSTALL_PREFIX:PATH=${install_prefix}
      -DCMAKE_SKIP_RPATH:BOOL=OFF
      -DCMAKE_SKIP_INSTALL_RPATH:BOOL=OFF
      -DMACOSX_RPATH:BOOL=ON
      -DCMAKE_INSTALL_RPATH:PATH=${install_prefix}/lib${LIB_SUFFIX}
      -DINSTALL_LIB_DIR:PATH=${install_prefix}/lib${LIB_SUFFIX}
      -DINSTALL_INC_DIR:PATH=${install_prefix}/include
      ${CMAKE_EXTERNAL_PROJECT_ARGS}
  INSTALL_COMMAND $(MAKE) install DESTDIR=${staging_prefix}
  INSTALL_DIR ${staging_prefix}/${install_prefix}
)

SET(ZLIB_SHARED_LIB_SUFFIX ".so")

IF(APPLE)
  SET(ZLIB_SHARED_LIB_SUFFIX ".dylib")
ENDIF(APPLE)


SET(ZLIB_INCLUDE_DIR        ${staging_prefix}/${install_prefix}/include )
SET(ZLIB_STATIC_LIBRARY     ${staging_prefix}/${install_prefix}/lib/libz.a )
SET(ZLIB_SHARED_LIBRARY     ${staging_prefix}/${install_prefix}/lib/libz${ZLIB_SHARED_LIB_SUFFIX} )
SET(ZLIB_DIR                ${staging_prefix}/${install_prefix}/share/cmake/ZLIB/ )
SET(ZLIB_FOUND ON)

IF(MT_BUILD_SHARED_LIBS)
  SET(ZLIB_LIBRARY ${ZLIB_STATIC_LIBRARY} ) # FIXED to avoid issues with restricted paths in MacOSX
ELSE(MT_BUILD_SHARED_LIBS)
  SET(ZLIB_LIBRARY ${ZLIB_STATIC_LIBRARY} )
ENDIF(MT_BUILD_SHARED_LIBS)

# Create the ZLIB::ZLIB imported target so that downstream projects
# (e.g. libminc) can use target_link_libraries(... ZLIB::ZLIB)
IF(NOT TARGET ZLIB::ZLIB)
  # Ensure the include directory exists at configure time so that
  # CMake's INTERFACE_INCLUDE_DIRECTORIES validation passes.
  # The actual headers are populated when the ExternalProject builds.
  FILE(MAKE_DIRECTORY "${ZLIB_INCLUDE_DIR}")
  ADD_LIBRARY(ZLIB::ZLIB STATIC IMPORTED GLOBAL)
  SET_TARGET_PROPERTIES(ZLIB::ZLIB PROPERTIES
    IMPORTED_LOCATION             "${ZLIB_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${ZLIB_INCLUDE_DIR}"
  )
ENDIF()

configure_file(${CMAKE_SOURCE_DIR}/cmake-modules/ZLIB-config.cmake.install.in ${staging_prefix}/${install_prefix}/share/cmake/ZLIB/ZLIBConfig.cmake @ONLY )

endmacro(build_zlib)
