macro(build_libarchive install_prefix staging_prefix)

  SET(LIBARCHIVE_VERSION_STRING 3.8.6)
  SET(LIBARCHIVE_VERSION_MAJOR  3)
  SET(LIBARCHIVE_VERSION_MINOR  8)
  SET(LIBARCHIVE_VERSION_PATCH 6)

  if(CMAKE_EXTRA_GENERATOR)
    set(CMAKE_GEN "${CMAKE_EXTRA_GENERATOR} - ${CMAKE_GENERATOR}")
  else()
    set(CMAKE_GEN "${CMAKE_GENERATOR}")
  endif()

  set(CMAKE_EXTERNAL_PROJECT_ARGS
        -DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}
        -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
        -DCMAKE_LINKER:FILEPATH=${CMAKE_LINKER}
        "-DCMAKE_C_FLAGS:STRING=-fPIC ${CMAKE_C_FLAGS}"
        -DCMAKE_C_FLAGS_DEBUG:STRING=${CMAKE_C_FLAGS_DEBUG}
        -DCMAKE_C_FLAGS_MINSIZEREL:STRING=${CMAKE_C_FLAGS_MINSIZEREL}
        -DCMAKE_C_FLAGS_RELEASE:STRING=${CMAKE_C_FLAGS_RELEASE}
        "-DCMAKE_C_FLAGS_RELWITHDEBINFO:STRING=${CMAKE_C_FLAGS_RELWITHDEBINFO}"
        -DCMAKE_EXE_LINKER_FLAGS:STRING=${CMAKE_EXE_LINKER_FLAGS}
        -DCMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=${CMAKE_EXE_LINKER_FLAGS_DEBUG}
        -DCMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=${CMAKE_EXE_LINKER_FLAGS_MINSIZEREL}
        -DCMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=${CMAKE_EXE_LINKER_FLAGS_RELEASE}
        "-DCMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=${CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO}"
        -DCMAKE_MODULE_LINKER_FLAGS:STRING=${CMAKE_MODULE_LINKER_FLAGS}
        -DCMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=${CMAKE_MODULE_LINKER_FLAGS_DEBUG}
        -DCMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=${CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL}
        -DCMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=${CMAKE_MODULE_LINKER_FLAGS_RELEASE}
        "-DCMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=${CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO}"
        -DCMAKE_SHARED_LINKER_FLAGS:STRING=${CMAKE_SHARED_LINKER_FLAGS}
        -DCMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=${CMAKE_SHARED_LINKER_FLAGS_DEBUG}
        -DCMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=${CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL}
        -DCMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=${CMAKE_SHARED_LINKER_FLAGS_RELEASE}
        "-DCMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=${CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO}"
        -DCMAKE_STATIC_LINKER_FLAGS:STRING=${CMAKE_STATIC_LINKER_FLAGS}
        -DCMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=${CMAKE_STATIC_LINKER_FLAGS_DEBUG}
        -DCMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=${CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL}
        -DCMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=${CMAKE_STATIC_LINKER_FLAGS_RELEASE}
        "-DCMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=${CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO}"
        -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
  )
  
  if(APPLE)
    list(APPEND CMAKE_EXTERNAL_PROJECT_ARGS
      -DCMAKE_OSX_ARCHITECTURES:STRING=${CMAKE_OSX_ARCHITECTURES}
      -DCMAKE_OSX_SYSROOT:STRING=${CMAKE_OSX_SYSROOT}
      -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=${CMAKE_OSX_DEPLOYMENT_TARGET}
    )
  endif()

  SET(LIBARCHIVE_URL "https://www.libarchive.org/downloads/libarchive-3.8.6.tar.gz")

  ExternalProject_Add(LIBARCHIVE
    URL  "${LIBARCHIVE_URL}"
    UPDATE_COMMAND ""
    SOURCE_DIR LIBARCHIVE
    BINARY_DIR LIBARCHIVE-build
    LIST_SEPARATOR :::
    CMAKE_GENERATOR ${CMAKE_GEN}
    CMAKE_ARGS
        -DBUILD_SHARED_LIBS:BOOL=OFF
        -DCMAKE_INSTALL_PREFIX:PATH=${install_prefix}
        -DCMAKE_SKIP_RPATH:BOOL=OFF
        -DCMAKE_SKIP_INSTALL_RPATH:BOOL=OFF
        -DMACOSX_RPATH:BOOL=ON
        -DCMAKE_INSTALL_RPATH:PATH=${install_prefix}/lib${LIB_SUFFIX}
        -DINSTALL_LIB_DIR:PATH=${install_prefix}/lib${LIB_SUFFIX}
        -DINSTALL_INC_DIR:PATH=${install_prefix}/include
        -DENABLE_EXPAT:BOOL=OFF
        -DENABLE_OPENSSL:BOOL=OFF
        -DENABLE_LIBXML2:BOOL=OFF
        -DENABLE_LZMA:BOOL=OFF
        -DENABLE_ZSTD:BOOL=OFF
        -DENABLE_LZ4:BOOL=OFF
        -DENABLE_BZip2:BOOL=OFF
        -DENABLE_GRZIP:BOOL=OFF
        -DENABLE_ACL:BOOL=OFF
        -DENABLE_LIBB2:BOOL=OFF
        -DENABLE_LZMA:BOOL=OFF
        -DENABLE_COMPRESSION:BOOL=OFF
        -DENABLE_TEST:BOOL=OFF
        -DZLIB_INCLUDE_DIR:PATH=${ZLIB_INCLUDE_DIR}
        -DZLIB_LIBRARY:FILEPATH=${ZLIB_LIBRARY}
        ${CMAKE_EXTERNAL_PROJECT_ARGS}
    INSTALL_COMMAND $(MAKE) install DESTDIR=${staging_prefix} 
    INSTALL_DIR ${staging_prefix}/${install_prefix}
  )

  SET(LIBARCHIVE_INCLUDE_DIR        ${staging_prefix}/${install_prefix}/include )
  SET(LIBARCHIVE_STATIC_LIBRARY     ${staging_prefix}/${install_prefix}/lib/libarchive.a )
  SET(LIBARCHIVE_SHARED_LIBRARY     ${staging_prefix}/${install_prefix}/lib/libarchive${CMAKE_SHARED_LIBRARY_SUFFIX} )
  SET(LIBARCHIVE_DIR                ${staging_prefix}/${install_prefix}/share/cmake/libarchive/ )
  SET(LIBARCHIVE_FOUND ON)
  SET(LibArchive_FOUND ON)

  IF(MT_BUILD_SHARED_LIBS)
    SET(LIBARCHIVE_LIBRARY ${LIBARCHIVE_STATIC_LIBRARY} )
  ELSE(MT_BUILD_SHARED_LIBS)
    SET(LIBARCHIVE_LIBRARY ${LIBARCHIVE_STATIC_LIBRARY} )
  ENDIF(MT_BUILD_SHARED_LIBS)

  SET(LIBARCHIVE_LIBRARIES ${LIBARCHIVE_LIBRARY})
  SET(LIBARCHIVE_INCLUDE_DIRS ${LIBARCHIVE_INCLUDE_DIR})
  SET(LibArchive_LIBRARIES ${LIBARCHIVE_LIBRARY})
  SET(LibArchive_INCLUDE_DIRS ${LIBARCHIVE_INCLUDE_DIR})

  FILE(MAKE_DIRECTORY ${LIBARCHIVE_INCLUDE_DIR})
  ADD_LIBRARY(libarchive STATIC IMPORTED GLOBAL)
  SET_TARGET_PROPERTIES(libarchive PROPERTIES
    IMPORTED_LOCATION             "${LIBARCHIVE_STATIC_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${LIBARCHIVE_INCLUDE_DIR}"
  )
  ADD_DEPENDENCIES(libarchive LIBARCHIVE)

  if(NOT USE_SYSTEM_ZLIB)
    ADD_DEPENDENCIES(LIBARCHIVE ZLIB)
  endif()

endmacro(build_libarchive)
