macro(build_nifti install_prefix staging_prefix)

  if(CMAKE_EXTRA_GENERATOR)
    set(CMAKE_GEN "${CMAKE_EXTRA_GENERATOR} - ${CMAKE_GENERATOR}")
  else()
    set(CMAKE_GEN "${CMAKE_GENERATOR}")
  endif()
  
  set(CMAKE_EXTERNAL_PROJECT_ARGS
        -DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}
        -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
        -DCMAKE_LINKER:FILEPATH=${CMAKE_LINKER}
        -DCMAKE_CXX_FLAGS:STRING=${CMAKE_CXX_FLAGS}
        -DCMAKE_CXX_FLAGS_DEBUG:STRING=${CMAKE_CXX_FLAGS_DEBUG}
        -DCMAKE_CXX_FLAGS_MINSIZEREL:STRING=${CMAKE_CXX_FLAGS_MINSIZEREL}
        -DCMAKE_CXX_FLAGS_RELEASE:STRING=${CMAKE_CXX_FLAGS_RELEASE}
        -DCMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=${CMAKE_CXX_FLAGS_RELWITHDEBINFO}
        -DCMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}
        -DCMAKE_C_FLAGS_DEBUG:STRING=${CMAKE_C_FLAGS_DEBUG}
        -DCMAKE_C_FLAGS_MINSIZEREL:STRING=${CMAKE_C_FLAGS_MINSIZEREL}
        -DCMAKE_C_FLAGS_RELEASE:STRING=${CMAKE_C_FLAGS_RELEASE}
        -DCMAKE_C_FLAGS_RELWITHDEBINFO:STRING=${CMAKE_C_FLAGS_RELWITHDEBINFO}
        -DCMAKE_EXE_LINKER_FLAGS:STRING=${CMAKE_EXE_LINKER_FLAGS}
        -DCMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=${CMAKE_EXE_LINKER_FLAGS_DEBUG}
        -DCMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=${CMAKE_EXE_LINKER_FLAGS_MINSIZEREL}
        -DCMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=${CMAKE_EXE_LINKER_FLAGS_RELEASE}
        -DCMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=${CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO}
        -DCMAKE_MODULE_LINKER_FLAGS:STRING=${CMAKE_MODULE_LINKER_FLAGS}
        -DCMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=${CMAKE_MODULE_LINKER_FLAGS_DEBUG}
        -DCMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=${CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL}
        -DCMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=${CMAKE_MODULE_LINKER_FLAGS_RELEASE}
        -DCMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=${CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO}
        -DCMAKE_SHARED_LINKER_FLAGS:STRING=${CMAKE_SHARED_LINKER_FLAGS}
        -DCMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=${CMAKE_SHARED_LINKER_FLAGS_DEBUG}
        -DCMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=${CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL}
        -DCMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=${CMAKE_SHARED_LINKER_FLAGS_RELEASE}
        -DCMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=${CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO}
        -DCMAKE_STATIC_LINKER_FLAGS:STRING=${CMAKE_STATIC_LINKER_FLAGS}
        -DCMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=${CMAKE_STATIC_LINKER_FLAGS_DEBUG}
        -DCMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=${CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL}
        -DCMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=${CMAKE_STATIC_LINKER_FLAGS_RELEASE}
        -DCMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=${CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO}
        -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
  )
  
  if(APPLE)
    list(APPEND CMAKE_OSX_EXTERNAL_PROJECT_ARGS
      -DCMAKE_OSX_ARCHITECTURES:STRING=${CMAKE_OSX_ARCHITECTURES_EXTSEP}
      -DCMAKE_OSX_SYSROOT:STRING=${CMAKE_OSX_SYSROOT}
      -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=${CMAKE_OSX_DEPLOYMENT_TARGET}
    )
  endif()

  set_property(DIRECTORY PROPERTY EP_STEP_TARGETS configure build test)

  SET(HDF_CMAKE_CXX_FLAGS_RELEASE ${CMAKE_CXX_FLAGS_RELEASE})
  SET(HDF_CMAKE_C_FLAGS_RELEASE   ${CMAKE_C_FLAGS_RELEASE})
  
  SET(HDF_CMAKE_CXX_FLAGS_DEBUG   ${CMAKE_CXX_FLAGS_DEBUG})
  SET(HDF_CMAKE_C_FLAGS_DEBUG     ${CMAKE_C_FLAGS_DEBUG})
  
  SET(NIFTI_CMAKE_CXX_FLAGS "-fPIC ${CMAKE_CXX_FLAGS} -I${ZLIB_INCLUDE_DIR}")
  SET(NIFTI_CMAKE_C_FLAGS   "-fPIC ${CMAKE_C_FLAGS} -I${ZLIB_INCLUDE_DIR}")

  # nifti_clib upstream (NIFTI-Imaging) has been dormant since v3.0.0 (2020);
  # the ITK fork is the maintained line and carries the bug fixes ITK ships.
  # It has no tags, so the pin is a commit SHA. Keep this pin in sync with
  # libminc/cmake-modules/BuildNIFTI.cmake, and regenerate nifti_mangle.h
  # (see the recipe in its header) whenever it moves.
  SET(NIFTI_GIT_SHA f24a607843c1fe4726ad774d0476bdf36bc11f2a)
  GET_PACKAGE("https://github.com/InsightSoftwareConsortium/nifti_clib/archive/${NIFTI_GIT_SHA}.tar.gz" "7099e80a905e26e0e2eb22f07c8a7faf" "nifti_clib-${NIFTI_GIT_SHA}.tar.gz" NIFTILIB_PATH )

  ExternalProject_Add(NIFTI
    SOURCE_DIR NIFTI
    BINARY_DIR NIFTI-build
    URL "${NIFTILIB_PATH}"
    URL_HASH SHA256=1829700c16ac0679487d9b7eb1d8d63a5d8a045e990d4b37b38f4760499aea16
    LIST_SEPARATOR :::
    # Mangle all exported nifti/znz symbols to a minc_ prefix so libminc's copy
    # cannot collide with ITK's own bundled niftiio (ITK has no
    # ITK_USE_SYSTEM_NIFTI switch). Single source of truth lives in the libminc
    # submodule (nifti_mangle.h / PatchNiftiMangle.cmake), used identically by
    # libminc's standalone BuildNIFTI and here in the superbuild.
    PATCH_COMMAND ${CMAKE_COMMAND}
        -DSRC=<SOURCE_DIR>
        -DMANGLE=${CMAKE_SOURCE_DIR}/libminc/cmake-modules/nifti_mangle.h
        -P ${CMAKE_SOURCE_DIR}/libminc/cmake-modules/PatchNiftiMangle.cmake
    CMAKE_GENERATOR ${CMAKE_GEN}
    CMAKE_ARGS
            -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
            -DBUILD_SHARED_LIBS:BOOL=OFF
            -DCMAKE_SKIP_RPATH:BOOL=OFF
            -DCMAKE_SKIP_INSTALL_RPATH:BOOL=OFF
            -DMACOSX_RPATH:BOOL=ON
            -DCMAKE_INSTALL_RPATH:PATH=${install_prefix}/${CMAKE_INSTALL_LIBDIR}
            -DCMAKE_INSTALL_PREFIX:PATH=${install_prefix}
            -DCMAKE_INSTALL_LIBDIR:PATH=${CMAKE_INSTALL_LIBDIR}
            # NIFTI's CMakeLists uses its own NIFTI_INSTALL_LIBRARY_DIR variable
            # (default 'lib'), not CMAKE_INSTALL_LIBDIR. Override it explicitly so
            # libniftiio.a / libznz.a end up in lib64 on Fedora x86_64. ARCHIVE_DIR
            # inherits from LIBRARY_DIR per NIFTI's own logic.
            -DNIFTI_INSTALL_LIBRARY_DIR:PATH=${CMAKE_INSTALL_LIBDIR}
            "-DCMAKE_CXX_FLAGS_RELEASE:STRING=${NIFTI_CMAKE_CXX_FLAGS_RELEASE}"
            "-DCMAKE_C_FLAGS_RELEASE:STRING=${NIFTI_CMAKE_C_FLAGS_RELEASE}"
            "-DCMAKE_CXX_FLAGS_DEBUG:STRING=${NIFTI_CMAKE_CXX_FLAGS_DEBUG}"
            "-DCMAKE_C_FLAGS_DEBUG:STRING=${NIFTI_CMAKE_C_FLAGS_DEBUG}"
            "-DCMAKE_CXX_FLAGS:STRING=${NIFTI_CMAKE_CXX_FLAGS}"
            "-DCMAKE_C_FLAGS:STRING=${NIFTI_CMAKE_C_FLAGS}"
            -DCMAKE_EXE_LINKER_FLAGS:STRING=${CMAKE_EXE_LINKER_FLAGS}
            -DCMAKE_MODULE_LINKER_FLAGS:STRING=${CMAKE_MODULE_LINKER_FLAGS}
            -DCMAKE_SHARED_LINKER_FLAGS:STRING=${CMAKE_SHARED_LINKER_FLAGS}
            -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
            -DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}
            -DZLIB_INCLUDE_DIR:PATH=${ZLIB_INCLUDE_DIR}
            -DZLIB_LIBRARY:FILEPATH=${ZLIB_LIBRARY}
            -DGIT_REPO_VERSION:STRING=3.0.0
            -DNIFTI_BUILD_APPLICATIONS:BOOL=OFF
            -DNIFTI_BUILD_TESTING:BOOL=OFF
            -DBUILD_TESTING:BOOL=OFF
            -DUSE_NIFTI2_CODE:BOOL=OFF
            -DUSE_NIFTICDF_CODE:BOOL=OFF
            -DNIFTI_INSTALL_NO_DOCS:BOOL=ON
            ${CMAKE_OSX_EXTERNAL_PROJECT_ARGS}
    INSTALL_COMMAND $(MAKE) install DESTDIR=${staging_prefix}
    INSTALL_DIR ${staging_prefix}/${install_prefix}
  )

SET(NIFTI_LIBRARY     ${staging_prefix}/${install_prefix}/${CMAKE_INSTALL_LIBDIR}/libniftiio.a )
SET(NIFTI_INCLUDE_DIR ${staging_prefix}/${install_prefix}/include/nifti )
SET(ZNZ_LIBRARY       ${staging_prefix}/${install_prefix}/${CMAKE_INSTALL_LIBDIR}/libznz.a )
SET(ZNZ_INCLUDE_DIR   ${staging_prefix}/${install_prefix}/include/nifti )
SET(NIFTI_FOUND ON)

# Mirror the NIFTI::niftiio / NIFTI::znz imported targets that nifti_clib's own
# NIFTIConfig.cmake would provide, so consumers link the same way whether NIFTI
# came from here or from find_package(NIFTI CONFIG). The config package itself
# is not usable at this point: ExternalProject builds at build time, long after
# the ADD_SUBDIRECTORY()'d consumers are configured.
#
# Same shape as the ZLIB::ZLIB target in BuildZLIB.cmake, ADD_DEPENDENCIES
# included: that is what orders a consumer of the target after the
# ExternalProject that produces the archive.
FILE(MAKE_DIRECTORY "${NIFTI_INCLUDE_DIR}" "${ZNZ_INCLUDE_DIR}") # imported INTERFACE include dirs must exist at configure time

# nifti_clib links a math library only where one exists -- see its own
# NIFTI_SYSTEM_MATH_LIB, empty on WIN32 -- so do not hardcode m.
SET(NIFTI_INTERFACE_LIBS NIFTI::znz)
IF(UNIX)
  LIST(APPEND NIFTI_INTERFACE_LIBS m)
ENDIF()

IF(NOT TARGET NIFTI::znz)
  ADD_LIBRARY(NIFTI::znz STATIC IMPORTED GLOBAL)
  SET_TARGET_PROPERTIES(NIFTI::znz PROPERTIES
    IMPORTED_LOCATION             "${ZNZ_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${ZNZ_INCLUDE_DIR}"
    INTERFACE_LINK_LIBRARIES      ZLIB::ZLIB)
  ADD_DEPENDENCIES(NIFTI::znz NIFTI)
ENDIF()

IF(NOT TARGET NIFTI::niftiio)
  ADD_LIBRARY(NIFTI::niftiio STATIC IMPORTED GLOBAL)
  SET_TARGET_PROPERTIES(NIFTI::niftiio PROPERTIES
    IMPORTED_LOCATION             "${NIFTI_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${NIFTI_INCLUDE_DIR}"
    INTERFACE_LINK_LIBRARIES      "${NIFTI_INTERFACE_LIBS}")
  ADD_DEPENDENCIES(NIFTI::niftiio NIFTI)
ENDIF()

endmacro()

