SET(CPACK_RPM_PACKAGE_GROUP "Applications/Engineering")

SET(CPACK_RPM_PACKAGE_REQUIRES "" )

SET(CPACK_RPM_PACKAGE_AUTOREQPROV " no")

SET(CPACK_RPM_PACKAGE_RELOCATABLE OFF)

SET(CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION "/opt")
